### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by bugsounet** [eouia/MMM-Timetable#6]
Hi eouia,

I have 2 children, how can I configure this module to display a chosen schedule.
I have 2 CSV files (one for each children)

Thanks for your help

**Comment by eouia** [comment]
You can rotate 2 timetable from csv with this fields.
```js
schedules: [      
  {
    title: "John's schedule",
    file: "john.csv",
  },
  {
    title: "Jane's schedule",
    file: "jane.csv",
  }
],
```

**Comment by bugsounet** [comment]
OK, but we can't force display  for vocal control

**Comment by eouia** [comment]
There is no other feature to change each view of schedules by force except time.

**Comment by bugsounet** [comment]
I will fork your project and include this feature.

Actualy, MMM-timetable is hidden and i call it with vocal command.
I'm looking to display the schedule I want
(sorry for my bad english ! :)

**Comment by eouia** [comment]
Of course, you can do it by yourself. `draw()` is the main point to draw each schedule. Modify it as your wish.

**Comment by bugsounet** [comment]
ok, it's done ! :)

I see a bug in your `draw()` code :
 
you want to `clearTimeout(timer)` but timer is _undefined_
I see it when i want to display in console the timer number because when i call `draw()` ... i have another timer ...

you can see my `draw()` version in my fork

**Comment by eouia** [comment]
Hmmmm...  `timer` is defined here;
https://github.com/eouia/MMM-Timetable/blob/c0fc83655d8dc20ca1b2636d26084edd49d9bb82/MMM-Timetable.js#L139


So, it is working as my intention.
https://www.dropbox.com/s/21pwyqt1pih82sc/capture.mov?dl=0

**Comment by bugsounet** [comment]
Ah... you don't understand :(
ok , try this : 

> draw: function() {
>     this.today = moment().isoWeekday()
>     this.drawView(this.config.schedules[this.index])
>     this.index++;
>     var timer;
>     if (this.index >= this.config.schedules.length) {
>       this.index = 0
>     }
>     console.log("before clearTimeout timer number : " + timer);
>     clearTimeout(timer)
>     console.log("after clearTimeout timer number : " + timer);
>     timer = null
>     timer = setTimeout(()=>{
>       this.draw()
>     }, this.config.refreshInterval)
>    console.log("after setTimeout timer number : " + timer);
>   },

before clearTimeout : timer -> undefined
after clearTimeout : timer -> undefined
after setTimeout : timer -> 'timer number'
After  this.config.refreshInterval, it's the same result.

So ... i think you don't kill the timer because the timer var is undefined <-> clearTimeout(undefined);

For me clearTimeout is not needed because it's auto cleared by this.config.refreshInterval setTimeout

**Comment by eouia** [comment]
I know what you mean. :) 

This is just a trait of an old legacy habit of handling timeout/interval routine of mine.
Originally that `timer` variable was not a local variable in my development stage. that was `this.timer` and it was regarded as the **static** variable for keeping timer instance in recursive routine.
And to be compatible with old JavaScript legacy, I have a habit to use **clear** timer instance and **make as null**  together. In some old engine, `clearTimeout()` couldn't work so nicely. That is why I use the convention like that.

But at release moment, I realized there is no need to keep that variable as static. The only caller is itself by time, so it doesn't need to be static. So I changed `this.timer` to `timer` and left the clearing routines as it was because it is no harm code to be executed. 

Conclusively, that(undefined `timer`) is not the reason of your original issue. (Using multiple csv). It works without any problem for my purpose.

But for your second issue(controlling by external condition - e.g. voice), that `draw()` is not enough. `timer` should be stopped and be refreshed by force.  So that is why I've said you need to modify `draw()` for your purpose.

**Comment by eouia** [comment]
If you want to add the feature of `changing tables by force`, make a PR with modified README. I'll accept it. :D
